kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: demo-dev
  namespace: fleet-default
spec:
  repo: https://github.com/atoy3731/aws-howdypartner-demo.git
  branch: dev
  targets:
  - name: dev
    clusterSelector:
      matchLabels:
        env: dev
  paths:
  - ./automation/gitops-fleet/backend/
  - ./automation/gitops-fleet/frontend/