kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: demo-prod
  namespace: fleet-default
spec:
  repo: https://github.com/atoy3731/aws-howdypartner-demo.git
  branch: prod
  targets:
  - name: prod
    clusterSelector:
      matchLabels:
        env: prod
  paths:
  - ./automation/gitops-fleet/backend/
  - ./automation/gitops-fleet/frontend/