kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: airgapped-docs
  namespace: fleet-default
spec:
  repo: https://github.com/atoy3731/aws-howdypartner-demo.git
  branch: main
  targets:
  - clusterGroup: airgapped-docs
  paths:
  - "./carbide/airgapped-docs/helm"
