kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: kubewarden
  namespace: fleet-default
spec:
  repo: https://github.com/atoy3731/aws-howdypartner-demo.git
  branch: main
  targets:
  - clusterGroup: secured
  paths:
  - "./security/kubewarden/crds"
  - "./security/kubewarden/controller"
  - "./security/kubewarden/defaults"
  - "./security/kubewarden/policies"

