kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: neuvector
  namespace: fleet-default
spec:
  repo: https://github.com/atoy3731/aws-howdypartner-demo.git
  branch: kube
  targets:
  - clusterGroup: secured
  paths:
  - "./security-neuvector/crd"
  - "./security-neuvector/core"
